services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - ngrok
    command: >
      sh -c "sleep 4 && 
            python manage.py set_webhook_with_ngrok &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:8000"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040

volumes:
  my_db:
