services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - ngrok
      - db
      - redis
    command: >
      sh -c "python manage.py wait_and_set_webhook_with_ngrok &&
            python manage.py run_server_with_migrations"

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    command:
      - "http"
      - "http://localhost:8000"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040

  redis:
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379

  celery:
    build:
      context: .
    restart: always
    command: celery -A library_service worker --loglevel=INFO --without-gossip --without-mingle --without-heartbeat -Ofair --pool=solo
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-beat:
    build:
      context: .
    restart: always
    command: celery -A library_service beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
