# Generated by Django 5.1 on 2024-08-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HARD", "Hard cover"), ("SOFT", "Soft cover")], max_length=4
            ),
        ),
    ]
