# Generated by Django 5.0.8 on 2024-08-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_service", "0003_book_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("title", "author")},
        ),
    ]
