# Generated by Django 5.0.8 on 2024-08-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(max_length=2047),
        ),
    ]
